package com.appabc.datas.tool;

/**
 * @Description : 
 * @Copyright   : GL. All Rights Reserved
 * @Company     : 江苏国立网络技术有限公司
 * @author      : 黄建华
 * @version     : 1.0
 * @Create_Date  : 2014年12月17日 上午11:41:46
 */

public final class DataSystemConstant {

	/**********************相关表的主键的定义类型的ID**********************/
	/**合同信息表主键业务编号*/
	public static final String CONTRACTINFOID = "CONTRACTINFOID";
	/**合同操作记录表主键业务编号*/
	public static final String CONTRACTOPERATIONID = "CONTRACTOPERATIONID";
	/**合同议价表主键业务编号*/
	public static final String CONTRACTDISPRICEID = "CONTRACTDISPRICEID";
	/**合同取消表主键业务编号*/
	public static final String CONTRACTCANCELID = "CONTRACTCANCELID";
	/**合同仲裁表主键业务编号*/
	public static final String CONTRACTARBITRATIONID = "CONTRACTARBITRATIONID";
	
	
	/**********************相关表的主键的定义类型的ID**********************/
	
	
	/*************************相关信息提示语的key*************************/
	public static final String MESSAGEKEY_UNINSTALLGOODSTIPS = "UNINSTALLGOODSTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_APPLY_DISPRICE_TIPS = "CONTRACT_APPLY_DISPRICE_TIPS";
	
	public static final String MESSAGEKEY_CONTRACT_VALIDATE_PASS_TIPS = "CONTRACT_VALIDATE_PASS_TIPS";
	
	public static final String MESSAGEKEY_TOCONFIRMCONTRACTTIPS = "TOCONFIRMCONTRACTTIPS";
	
	public static final String MESSAGEKEY_NOTICESHIPPINGGOODSTIPS = "NOTICESHIPPINGGOODSTIPS";
	
	public static final String MESSAGEKEY_VALIDATEGOODSTIPS = "VALIDATEGOODSTIPS";
	
	public static final String MESSAGEKEY_FINALESTIMATEFINISHEDTIPS = "FINALESTIMATEFINISHEDTIPS";
	
	public static final String MESSAGEKEY_PAYCONTRACTFUNDSTIPS = "PAYCONTRACTFUNDSTIPS";
	
	public static final String MESSAGEKEY_MAKEANDMATCHAORDERTIPS = "MAKEANDMATCHAORDERTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_DIS_PRICE_TIPS = "CONTRACT_DIS_PRICE_TIPS";
	
	public static final String MESSAGEKEY_APPLYCONTRACTFINALESTIMATE = "APPLYCONTRACTFINALESTIMATE";
	
	public static final String MESSAGEKEY_FINISH_CONTRACT_TIPS = "FINISH_CONTRACT_TIPS";
	
	public static final String MESSAGEKEY_CANCELCONTRACTTIPS = "CANCELCONTRACTTIPS";
	
	public static final String MESSAGEKEY_TOCONTRACTARBITRATIONTIPS = "TOCONTRACTARBITRATIONTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_CONSULTING_SERVICETIPS = "CONTRACT_CONSULTING_SERVICETIPS";
	
	public static final String MESSAGEKEY_CONTRACT_ARBITRATION_PROCESSTIPS = "CONTRACT_ARBITRATION_PROCESSTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_OUT_OF_LIMITTIMETIPS = "CONTRACT_OUT_OF_LIMITTIMETIPS";
	
	public static final String MESSAGEKEY_CONTRACT_TO_CANCEL_TIMEOUT_FAILTIPS = "CONTRACT_TO_CANCEL_TIMEOUT_FAILTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_CONFIRM_TIMEOUT_FAILTIPS = "CONTRACT_CONFIRM_TIMEOUT_FAILTIPS";
	
	public static final String MESSAGEKEY_CONTRACT_CONFIRM_GOODS_TIPS = "CONTRACT_CONFIRM_GOODS_TIPS";
	
	public static final String MESSAGEKEY_CONTRACT_DEFAULT_EVALUATION_TIPS = "CONTRACT_DEFAULT_EVALUATION_TIPS";
	
	public static final String MESSAGEKEY_CONTRACT_MINI_EVALUATION_TIPS = "CONTRACT_MINI_EVALUATION_TIPS";
	
	public static final String MESSAGEKEY_CONTRACT_EVALUATION_ANONYMITYUNAME_TIPS = "CONTRACT_EVALUATION_ANONYMITYUNAME_TIPS";
	
	public static final String MESSAGEKEY_CONTRACT_BUYER_UNPAY_FINISHED_TIPS = "CONTRACT_BUYER_UNPAY_FINISHED_TIPS";
	
	public static final String MESSAGEKEY_ORDER_FIND_TIMEOUT_TIPS = "ORDER_FIND_TIMEOUT_TIPS";
	
	/*************************相关信息提示语的key*************************/
	
	
	/*************************异常消息的提示音key*************************/
	public static final String EXCEPTIONKEY_CONTRACT_UNINSTALLS_GOODS_NOTSELLER_ERROR = "CONTRACT_UNINSTALLS_GOODS_NOTSELLER_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_LIFECYCLEIS_ERROR = "CONTRACT_LIFECYCLEIS_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_JUST_ALLOW_APPLY_DISPRICE_ERROR = "CONTRACT_JUST_ALLOW_APPLY_DISPRICE_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_CONFIRM_CONTRACT_REPEAT_ERROR = "CONTRACT_CONFIRM_CONTRACT_REPEAT_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_NOALLOW_ERROR = "CONTRACT_NOALLOW_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_IDNOTALLOW_ERROR = "CONTRACT_IDNOTALLOW_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_RECEIVE_GOODS_NOTBUYER_ERROR = "CONTRACT_RECEIVE_GOODS_NOTBUYER_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_CONFIRM_CONTRACT_PAYSTATUS_ERROR = "CONTRACT_CONFIRM_CONTRACT_PAYSTATUS_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_CONFIRM_CONTRACT_NOBUYER_ERROR = "CONTRACT_CONFIRM_CONTRACT_NOBUYER_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_PAY_FUNDS_ERROR = "CONTRACT_PAY_FUNDS_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_REPEAT_SUBMIT_ERROR = "CONTRACT_REPEAT_SUBMIT_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_CONFIRM_CONTRACT_NOENOUGHGUANT_ERROR = "CONTRACT_CONFIRM_CONTRACT_NOENOUGHGUANT_ERROR";
	
	public static final String EXCEPTIONKEY_PARAMETER_IS_NOT_ALLOW_NULL_ERROR = "PARAMETER_IS_NOT_ALLOW_NULL_ERROR";
	
	public static final String EXCEPTIONKEY_IS_PARENT_ORDER = "IS_PARENT_ORDER";
	
	public static final String EXCEPTIONKEY_CONTRACT_JUST_ALLOW_DISPRICE_ERROR = "CONTRACT_JUST_ALLOW_DISPRICE_ERROR";
	
	public static final String EXCEPTIONKEY_CONTACT_FINALESTIMATE_NOTBUYER_ERROR = "CONTACT_FINALESTIMATE_NOTBUYER_ERROR";
	
	public static final String EXCEPTIONKEY_CONTACT_FINALESTIMATE_NOTSELLER_ERROR = "CONTACT_FINALESTIMATE_NOTSELLER_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_NOT_BUYER_SELLER_TOOPERATE_ERROR = "CONTRACT_NOT_BUYER_SELLER_TOOPERATE_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_NOT_ALLOW_CANCEL_ERROR = "CONTRACT_NOT_ALLOW_CANCEL_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_NOT_SUPPORT_OPERATETYPE_ERROR = "CONTRACT_NOT_SUPPORT_OPERATETYPE_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_CANCEL_AGAIN_ERROR = "CONTRACT_CANCEL_AGAIN_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_ARBITRATION_PRICE_NUM_ERROR = "CONTRACT_ARBITRATION_PRICE_NUM_ERROR";
	
	public static final String EXCEPTIONKEY_CONTACT_SELLER_BUYER_IS_SAME_ERROR = "CONTACT_SELLER_BUYER_IS_SAME_ERROR";
	
	public static final String EXCEPTIONKEY_CONTRACT_FINALESTIMATE_AMOUNT_SCOPE_ERROR = "CONTRACT_FINALESTIMATE_AMOUNT_SCOPE_ERROR";
	
	/*************************异常消息的提示音key*************************/
	
	
}
